### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by JIaxyga** [99degree/linux#1]
Sorry for writing here. I need to contact you regarding the touchscreen driver. Please contact me

**Comment by 99degree** [comment]
no problem i am more prefer to move the dev related matter into this issue pages, kind of.

if you really wanted to include the driver, i am afraid you need to spend some time to add support for nt36672c on your side. it depends on how different nt36675 and 36672c difference, such ad crc etc. initially i wonder if easily add nt36672c into the probe list is enough but, no idea. i can help to point out that.

https://github.com/99degree/linux/commit/405f5204bdebf64ec34cc2bf2cc5904e6ba2de51#r132885559

the driver default behavior is to expect each time panel sleep->wake up, fw need to download again. See if nt36672c work the same.

**Comment by JIaxyga** [comment]
I already added https://github.com/sm7150-mainline/linux/tree/surya-ts
I would like to talk about the features and improvements of the driver. So it would be more convenient to go to some messenger

**Comment by 99degree** [comment]
i made some comment here.
https://github.com/sm7150-mainline/linux/commit/e1795b0fa497624ca560e298f171db43ac3c3fd3#r132888905

and here
https://github.com/sm7150-mainline/linux/commit/49c5661410487db3afd67bd055a3fb24dfed36b8#r132889386

hope above helps.

**Comment by 99degree** [comment]
btw, i dont have plan to submit upstream, if you wanna to improve and submit to the kernel mailing list, please do so. dont hesitate! i am feeling great people get used of the code.

**Comment by JIaxyga** [comment]
I know a lot of people who have various nvt-ts-spi touchscreens (including goodix_ts_berlin), they are happy to participate in testing and development of the driver. It’s just that no one knew that the driver had already begun to be rewritten. Still a very good job! Thanks!

**Comment by JIaxyga** [comment]
But I would really like to contact you somewhere. It would be great if you joined https://matrix.to/#/#sm7150-mainline:matrix.org, we discuss sm7125 there too. ungeskriptet (who is upstreaming sm7125 at the moment) and jojo_autoboy (who is testing a lot of things on sm7125) are also in this chat. They will be happy to exchange experiences

**Comment by JIaxyga** [comment]
Adrian wants to run AOSP on sm7150-mainline, so he'd be happy too

**Comment by 99degree** [comment]
Hi JIaxyga,

Nice, great to hear that, and also appreciate your patches in mailing list. Unfortunately my poor little joyeuse is on EOL count down soon. I do not have plan to repair, mainly not financial worthy for at least battery replacement, back panel, volume key and checkup fee... Plz keep the good work!

Best wishes,
99degree

**Comment by JIaxyga** [comment]
> Hi JIaxyga,
> 
> Nice, great to hear that, and also appreciate your patches in mailing list. Unfortunately my poor little joyeuse is on EOL count down soon. I do not have plan to repair, mainly not financial worthy for at least battery replacement, back panel, volume key and checkup fee... Plz keep the good work!
> 
> Tribute to the great but poor little sm7125 phone https://www.youtube.com/watch?v=tx09_U4O6UQ
> 
> Best wishes, 99degree

Down key button doesnt work on the last next. I havent looked for the reason yet, so idk

All the best,
Danila

**Comment by 99degree** [comment]
feel the same, buddy. my side, i got physically damages of back panel, the batt expand (a bit risky) and down vol button fixture crack, it makes me enter fastboot not so easily. I really like to see if your side can get the modem or (eventually) wifi up. So on sm7125 chip it would be in very simple porting to make it work. see if that happened soon and i can help to test it on the breaky phone.

best wish!

**Comment by JIaxyga** [comment]
We have modem (for calls, SMS and mobile data), wifi, bt (gps works only by triangulation)

All the best,
Danila
